# 프로그램 오류, 예외 클래스의 계층구조

컴퓨터 하드웨어의 오작동 또는 고장으로 인해 응용프로그램 실행 오류가 발생하는 것을 에러(error)라고 하고, 이런 에러 상황을 처리하는것이 예외처리라고 함.

이를 통해 프로그램이 에러로 인해 강제 종료되는 것을 막고, 정상 실행 상태 유지가 가능.

## 예외는 언제 발생하는가?

```java
ex) 존재하지 않는 파일을 열기 위한 자바 코드.

import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;

public class ExceptionSample {
	public static void main(String[] args) throws IOException {
		BufferedReader br = new BufferedReader(new FileReader("존재하지_않는_파일"));
		br.readLine();
		br.close();
	}
}
//존재하지 않는 파일을 읽으려 하기 때문에, 원하는 파일을 찾을 수 없다는 오류가 발생.
//오류 : java.io.FileNotFoundException
```

이번에는 0으로 다른 숫자를 나누는 프로그램.

```java
public class DivideExceptionSample {
	public static void main(String[] args) {
		int result = 5 / 0;
	}
}
//자바에서는 숫자를 0으로 나눌 수 없기 때문에 산술에 문제가 생겼다는 오류가 발생.
//오류 : ArithmeticException
```

자바는 이와 같이 예외가 발생하면 **프로그램을 중단하고 오류 메시지를 출력**.

이때 프로그램 중단없이 오류 메시지를 출력하고 다음 프로세스로 넘어가도록 조치해줄 수 있는것이 자바에서의 예외처리를 뜻함.

## 예외 클래스의 계층 구조

예외 클래스에는 일반 예외와 실행 예외 두가지가 존재.

일반 예외는 컴파일러 체크 예외라고도 하는데, 컴파일러가 예외 처리를 강제하는 것으로, 일반적으로 개발자가 예측할 수 있는 상황에서 발생하며, 예외 처리 코드를 반드시 작성해야 함. 만약 예외 처리 코드가 없다면 컴파일 오류가 발생.

### 주요 예외 클래스

1. **IOException :** 입출력 관련 작업에서 발생하는 예외를 처리하는 클래스.
2. **FileNotFoundException :** 파일을 찾을 수 없을 때 발생하는 예외를 처리하는 클래스.
3. **ClassNotFoundException :** 클래스를 찾을 수 없을 때 발생하는 예외를 처리하는 클래스.
4. **SQLException :** 데이터베이스 작업 중에 발생하는 예외를 처리하는 클래스.

실행 예외는 컴파일러가 예외 처리를 강제하지 않는 예외로, 일반적으로 개발자의 실수로 인해 발생하며, 예외 처리를 강제하지 않지만 컴파일시 예외 처리를 확인하는 차이일 뿐, 두 가지 예외는 모두 예외 처리가 필요.

### 주요 예외 클래스

1. **NullPointerException :** null 객체 참조 시에 발생하는 예외를 처리하는 클래스.
2. **ArrayIndexOutOfBoundsException :** 배열의 범위를 초과하여 접근 시에 발생하는 예외를 처리하는 클래스.
3. **ClassCastException :** 클래스 캐스팅이 잘못되었을 때 발생하는 예외를 처리하는 클래스.
4. **NumberFormatException :** 숫자 형식이 아닌 문자열을 숫자로 변환 시도 시에 발생하는 예외를 처리하는 클래스.

![map](https://github.com/HuiGyun-kim/TIL/assets/105576581/4fe0d1da-9e89-410b-8adf-ed16154df5bb)

- 모든 객체의 최상위 부모가 Object이듯, 예외도 최상위 부모는 Object
- Throwable : 최상위 예외.
- Error : 메모리 부족이나 심각한 시스템 오류같은 복구 불가능한 예외. 개발자가 잡을 수 없는 예외.
- Exception : 컴파일러가 체크하는 checked exception. 단 RuntimeException은 예외.
- RuntimeException : 컴파일러가 체크하지 않는 unchecked exception, 런타임 예외.

# 예외 처리 try-catch

## try-catch문

앞서 살펴본 예외들을 처리하기 위해 try-catch문을 사용.

```java
//try-catch문의 기본 구조.
try {
    <수행할 문장 1>;
    <수행할 문장 2>;
    ...
} catch(예외1) {
    <수행할 문장 A>;
    ...
} catch(예외2) {
    <수행할 문장 a>;
    ...
}
```

- 첫 번째 코드의 try문 에서 예외가 발생하여 catch 예외1이 수행된다면 그 다음 예외2의 catch문은 수행되지 않음.
- try문 안의 수행할 문장 중 예외가 발생하지 않는다면 catch문 안의 내용은 수행되지 않음.

```java
import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;

public class ExceptionSample {
	public static void main(String[] args) throws IOException {
		BufferedReader br = new BufferedReader(new FileReader("존재하지_않는_파일"));
		br.readLine();
		br.close();
	}
}

//예외 처리 이후
public class ExceptionSample {
	public static void main(String[] args) {
		try {
			BufferedReader br = new BufferedReader(new FileReader("존재하지_않는_파일"));
			br.readLine();
			br.close();
		} catch (IOException e) {
			System.out.println("error message: " + e.getMessage());
		}
	}
}
//error message: 존재하지_않는_파일 (No such file or directory)
```

다른 예시)

0으로 숫자를 나눴을 때 ArithmeticException이 발생하고, ArithmeticException은 실행 예외지만 모든 에러는 예외처리가 필요하기 때문에 try-catch문을 사용하여 아래와 같이 코드를 작성.

```java
public class DivideExceptionSample {
	public static void main(String[] args) {
		int result;
		try {
			result = 5 / 0;
		} catch (ArithmeticException e) {
			result = -1;
			System.out.println("숫자는 0으로 나눌 수 없습니다.");
		}
	}
}
//출력 결과 : 숫자는 0으로 나눌 수 없습니다.
```

### 다중 catch문 작성시 주의사항

상위 예외클래스가 하위 예외 클래스보다 아래쪽에 위치해야한다는 것.

```java
try {
	(ArrayIndexOutOfBoundsException 발생)
	(NumberFormatException 발생)
} catch(Exception e) {
	예외처리1
} catch(ArrayIndexOutOfBoundsException e) {
	예외처리2    // 컴파일 오류
}

//변경후
try {
	(ArrayIndexOutOfBoundsException 발생)
	(NumberFormatException 발생)
} catch(ArrayIndexOutOfBoundsException e) {
	예외처리1
} catch(Exception e) {
	예외처리2
}
```

이 코드에서 ArrayIndexOutOfBoundsException 예외와 NumberFormatException 예외는 모두 Exception을 상속받기 때문에 첫번째 catch 블록만 선택되어 실행되기 때문에 두번째 catch블록은 무시.

try 블록에서 ArrayIndexOutOfBoundsException이 발생하면 첫번째 catch 블록을 실행하고, 그 밖의 다른 예외가 발생하면 두 번째 catch 블록을 실행.

## finally

프로그램 수행 도중 에러가 발생하면 프로그램이 중단되거나 예외 처리에 의해 catch 구문이 실행되지만 어떤 예외가 발생하더라도 반드시 실행되는 부분이 있는데, 바로 **finally** 구문임.

![finally](https://github.com/HuiGyun-kim/TIL/assets/105576581/844ca6a0-78d5-455c-9fed-c8b1d9e1a7ce)

```java
public class DivideExceptionSample {
    void finalMessage() {
        System.out.println("그럼 수고하세요.");
    }

    public static void main(String[] args) {
        DivideExceptionSample sample = new DivideExceptionSample();
        int result;
        try {
            result = 5 / 0;
            sample.finalMessage();       // 이 코드는 실행되지 않는다.
        } catch (ArithmeticException e) {
            result = -1;
            System.out.println("숫자는 0으로 나눌 수 없습니다.");
        } finally {
            sample.finalMessage();    // 이곳에서는 예외와 상관없이 무조건 수행된다.
        }
    }
}
```

```
💡 하루 10개 질문
```


| 번호 | 질문 |
| --- | --- |
| 1 | 자바에서 예외 처리를 하는 주된 목적은 무엇인가요? |
| 2 | 체크 예외와 실행 예외의 차이점에 대해 구체적으로 설명할 수 있나요? |
| 3 | Throwable 클래스와 Error, Exception, RuntimeException 클래스 간의 관계를 설명할 수 있나요? |
| 4 | 예외 처리를 위한 try-catch문의 작동 원리를 설명할 수 있나요? |
| 5 | 예외 처리를 잘못 구현했을 때 발생할 수 있는 문제점과 이를 예방하기 위한 좋은 예외 처리 방법은 무엇인가요? |
| 6 | try-catch-finally 문에서 finally 블록이 항상 실행되는 경우와 실행되지 않는 경우를 설명할 수 있나요? |
| 7 | 다중 catch 문에서 예외 처리 순서가 왜 중요한가요? 잘못된 순서로 작성했을 때의 문제점은 무엇인가요? |
| 8 | RuntimeException과 Error의 차이점은 무엇이며, 각각 어떤 경우에 사용되나요? |
| 9 | 프로그램에서 예외를 무시하기 위해 catch 블록을 비워두는 것이 권장되지 않는 이유는 무엇인가요? |
| 10 | Error 클래스의 예외는 대부분 복구 불가능한 예외로 설명되는데, 이런 상황에서 개발자가 취할 수 있는 조치가 있나요? |